services:
  ham_conditions:
    build: .
    ports:
      - "8087:8087"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - ZIP_CODE=${ZIP_CODE}
      - TEMP_UNIT=${TEMP_UNIT:-F}
      - CALLSIGN=${CALLSIGN}
      - DATABASE_PATH=/app/data/ham_radio.db
      - DATA_RETENTION_DAYS=7
    volumes:
      - .:/app
      - ham_radio_data:/app/data
      - ham_radio_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ham_radio_data:
  ham_radio_logs: 
