services:
  ham_conditions:
    build: .
    ports:
      - "8087:8087"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - ZIP_CODE=${ZIP_CODE}
      - TEMP_UNIT=${TEMP_UNIT:-F}
      - CALLSIGN=${CALLSIGN}
    volumes:
      - .:/app
    restart: unless-stopped 
